### ISSUE TITLE
生成代码功能没有效果？

### ISSUE THREAD

**Issue by cilla123** [MQEnergy/MQCMS-admin#2]
后台的http://localhost:8080/#/setting/table，这个页面里面的“生成代码功能”点击没效果，看了代码，好像只有预览

**Comment by chenxi2015** [comment]
> 后台的[http://localhost:8080/#/setting/table，这个页面里面的“生成代码功能”点击没效果，看了代码，好像只有预览](http://localhost:8080/#/setting/table%EF%BC%8C%E8%BF%99%E4%B8%AA%E9%A1%B5%E9%9D%A2%E9%87%8C%E9%9D%A2%E7%9A%84%E2%80%9C%E7%94%9F%E6%88%90%E4%BB%A3%E7%A0%81%E5%8A%9F%E8%83%BD%E2%80%9D%E7%82%B9%E5%87%BB%E6%B2%A1%E6%95%88%E6%9E%9C%EF%BC%8C%E7%9C%8B%E4%BA%86%E4%BB%A3%E7%A0%81%EF%BC%8C%E5%A5%BD%E5%83%8F%E5%8F%AA%E6%9C%89%E9%A2%84%E8%A7%88)

目前还在开发阶段，暂不能用于生产
